version: "3.8"

services:
  app:
    image: php:fpm
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  webserver:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
